### ISSUE TITLE
Chrome 128.0.6613.138   Failed to find the first pattern!

### ISSUE THREAD

**Issue by Fomovet** [Meckazin/ChromeKatz#10]
[*] Targeting Chrome
[+] Found browser process: 19932
    Process owner: DESKTOP-AH5JX\Admin
[-] Failed to find the first pattern!`

Can you also provide a method to find the offset of the new version so that I can find and replace it myself next time there is a new version?

**Comment by Meckazin** [comment]
Fixed in the latest version.
